parameters:
    routing.uuid: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    routing.md5: '[0-9a-f]{32}'
    env(APP_SECRET): ''
    env(APP_BASEURL_FRONTEND): 'http://localhost'
    env(CORS_ALLOW_ORIGIN): '*'
    env(DATABASE_URL): ''
    env(DATABASE_SERVER_VERSION): 'mariadb-10.6.3'
    env(LOCK_DSN): 'semaphore'
    env(MAILER_DSN): ''
    env(MAILER_FROM): 'mail@localhost'
    
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Twig\Extra\CssInliner\CssInlinerExtension: ~
    Twig\Extra\Inky\InkyExtension: ~

    Symfony\Component\Security\Core\User\UserProviderInterface: '@security.user.provider.concrete.all_users'