controllers:
    resource: ../../src/Controller/
    exclude:
        - ../../src/Controller/Api/*
        - ../../src/Controller/Files/*
        - ../../src/Controller/Images/*
    type: annotation

api_controllers:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api/v{version}
    defaults:
        _format: json
    requirements:
        version: \d+

files_controllers:
    resource: ../../src/Controller/Files/
    type: annotation
    prefix: /files

image_controllers:
    resource: ../../src/Controller/Images/
    type: annotation
    prefix: /images

kernel:
    resource: ../../src/Kernel.php
    type: annotation
